# Site settings

title: Arnaud Hervy, Technical Writer
author: Arnaud Hervy
email: arnaud.hervy@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Technical Writing portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arnaudhervy.com" # the base hostname & protocol for your site, e.g. http://example.com

sass:
  sass_dir: assets/css
  style: compressed

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "assets/pdf/*.pdf"
    values:
      sitemap: false

# Build settings

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
