baseURL = "https://arnaudhervy.com/"
languageCode = "en-us"
title = "Arnaud Hervy"
theme = ["PaperMod"]
pluralizelisttitles = false

[params]
env = "production"
title = "Arnaud Hervy"
ShowBreadCrumbs = true

  [params.profileMode]
  enabled = true
  title = "Arnaud Hervy"
  subtitle = "Technical writer and certified UX writer"
  imageUrl = "/profile-picture.jpg"
  imageTitle = "Profile picture"
  imageWidth = 120
  imageHeight = 120

    [[params.profileMode.buttons]]
    name = "Get to know me"
    url = "/about/"
    
    [[params.profileMode.buttons]]
    name = "View work samples"
    url = "/portfolio/"

  [[params.socialIcons]]
  name = "Github"
  url = "https://github.com/ahervy"

  [[params.socialIcons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/arnaudhervy/"

[[menu.main]]
identifier = "about"
name = "About me"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 20

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 30