baseURL = "https://arnaudhervy.com/"
languageCode = 'en-us'
theme = ["limpide"]
pluralizelisttitles = false
title = "Arnaud Hervy"


[params]
  env = "production"
  author = "Arnaud Hervy"
  description = "Technical writer and certified UX writer"
  introText = "I'm a technical writer and certified UX writer."

  [[params.introButtons]]
    label = "Get to know me"
    url = "/about/"

  [[params.introButtons]]
    label = "See my work"
    url = "/portfolio/"

[menu]
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 10

  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 20

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 30